### ISSUE TITLE
Feature Request: Push Notification(APNS)

### ISSUE THREAD

**Issue by dreampiggy** [CoderxforGitHub/Feedback#28]
Hi. I'm a user who recently try thte Grape for GitHub. Previously I'm using another popular iOS GitHub client [CodeHub](https://github.com/CodeHubApp/CodeHub). It has a best feature useful for me, the push notification.

CodeHub Pro IAP (cost $2) will enable the Push Notification feature. If everytime a new notification from GitHub.com triggered, such as a new comment, a new PR for your repo, a new release for watched repo, they will send you a Push Notification as well. It can help me to get the response from open-source user as quickly as possible.

But however, CodeHub seems lack of some easy-to-use feature, including **modify the comment**, **submit a emoji**, **review the PR's changes**. So everytime I just need to use the In-App webview to help for this...It's really disappointed. During my usage, I found these feature is right available by the Grape for Github with a native user interface, it's good.

So if this feature can be available soon, I can totally switch from CodeHub to the Grape, instead of installing both two of them 😅

**Comment by derekcoder** [comment]
Thank you very much for your feedback. The notification feature is already in the list of my development features. However, since GitHub does not give direct notifications api, if I want to do it now, one of the methods is to upload the user's authrization code to the server, and then periodically call the github api. This can be a security risk for users with private repositories. I am still considering other methods, such as background fetch. If any update, I will let you know.

**Comment by barbequesauce** [comment]
Hi - I love Coderx / Grape too, but I also have another GH app installed for push notifications (GitHawk in my case). Hoping this gets added to Grape soon!

**Comment by derekcoder** [comment]
@dreampiggy @barbequesauce The push notification function is currently in beta. Expected to be released in the next week.

**Comment by derekcoder** [comment]
@dreampiggy @barbequesauce  v3.0 released with push notification support. Please update and have a try. If you have any other problems, feel free to create a new issue.

**Comment by barbequesauce** [comment]
Hi - any idea how long it should take for the notification to fire? I’m current per TestFlight but unopened notifications on the website do not seem to be noticed by CoderX...
