### ISSUE TITLE
Improvements for notifications list

### ISSUE THREAD

**Issue by dimirc** [CoderxforGitHub/Feedback#43]
- Maybe faster access (using an icon at main bottom bar) will be better for notifications as they are one of the main reason we, and maybe many user are using the app.
- User colors for the icons at notifications, it’s complicated to read without colors. Right now I have about 300 notifications and at the web version of GitHub I normally use the color as a fast way to find and organize what to check first
- Make project info smaller at notification list, it’s taking too much space and in my case 300 notification with 300 times showing the same project name and description is not optimal. Maybe just create a section/group by project similar to how GitHub web version works

iPhone Xs 12.1.2 - V2.11.1(229)

**Comment by derekcoder** [comment]
@dimirc thank you for your feedback. For the first one, you can customize your tabbar using "Customize Tab Bar" in Setttings. I will add others into my development plan.
