### ISSUE TITLE
org不显示

### ISSUE THREAD

**Issue by Pircate** [CoderxforGitHub/Feedback#48]
加入的组织不能显示。

iPhone Xr 12.2 - V2.11.2(232)

**Comment by derekcoder** [comment]
@Pircate 你好。问下你加入的组织是私有的吗？因为我从 GitHub 网站看你的个人信息，没发现你有组织。

**Comment by derekcoder** [comment]
@Pircate 你好。一般情况下，如果你加入的组织没有显示，是因为你没有申请访问该组织的权限。账号页面的底部有一个检查你的 GitHub 访问权限的链接，你看下是否是没有访问该组织的权限。
