### ISSUE TITLE
排行榜有bug

### ISSUE THREAD

**Issue by mm2m123** [CoderxforGitHub/Feedback#54]
每次刷新排行榜内容和排名都不一样。

iPhone Xs Max 12.2 - V2.12.2(251)

**Comment by derekcoder** [comment]
@mm2m123 你好。我测试几次，没发现排行榜会随着每次刷新变化。一般每天才会变一次。如果方便的话，可否帮忙录个视频。这个我会更容易定位问题。感谢反馈。
