### ISSUE TITLE
无法显示已加入的组织

### ISSUE THREAD

**Issue by Thesharing** [CoderxforGitHub/Feedback#56]
点击组织，显示组织为空。

iPhone SE 12.2 - V2.13.0(253)

**Comment by derekcoder** [comment]
@Thesharing 你好。可以给我发张截图吗？我这边可以看到你的组织。

![IMG_3589](https://user-images.githubusercontent.com/19852435/56704072-4da80100-673e-11e9-89bc-e938eb5383aa.PNG)
![IMG_3588](https://user-images.githubusercontent.com/19852435/56704080-53054b80-673e-11e9-9f0d-b3abe90db6f7.PNG)

**Comment by Thesharing** [comment]
![screenshot-1](https://user-images.githubusercontent.com/6576831/56721764-253cf880-6778-11e9-96b6-0c04efe772ab.png)
![screenshot-2](https://user-images.githubusercontent.com/6576831/56721765-25d58f00-6778-11e9-87bb-0577ef85b657.png)

是因为和成员在组织内的可见性有关系吗？

**Comment by derekcoder** [comment]
有可能，我先尝试复现下。可能后面还需要你的帮忙。很开心你喜欢这个 App，我继续优化和添加新功能的。

**Comment by lbj2018** [comment]
@Thesharing 问下你在组织里是member还是 admin？我还是没法复现。

**Comment by derekcoder** [comment]
@Thesharing 我还是没法复现😭。请问下你在组织的 Role 是什么？member 还是 admin？

**Comment by Thesharing** [comment]
我应该是有四个组织，DanmakuPie这个是Owner，且Membership为Public；Awesome-Interview是Owner，但是Membership为Private；Awesome BUPT和19KG为Member，Membership为Private。

**Comment by derekcoder** [comment]
我应该知道是什么问题了。下面这个链接是检查你的 GitHub 账号在当前这个 App 中的权限的。你看看是不是没有申请访问组织的权限。

https://github.com/settings/connections/applications/6a21589653956ffabb4c

**Comment by derekcoder** [comment]
如果没有，点击 grant 就可以了。

**Comment by lbj2018** [comment]
@Thesharing 如果解决了，让我知道下。

**Comment by derekcoder** [comment]
@Thesharing 如果解决了，让我知道下。

**Comment by Thesharing** [comment]
Okay，已经解决了~ 十分感谢 ^-^
