### ISSUE TITLE
通知标签，建议取消滑动至底部自动更新

### ISSUE THREAD

**Issue by walterlv** [CoderxforGitHub/Feedback#57]
## 问题

在查看通知，滑倒最底端后，会自动刷新，导致每次都看不到最底部的通知。

## 建议

任何一条，或者你的想法

1. 取消滑动至底部自动刷新；
2. 刷新后保留阅读位置。

**Comment by derekcoder** [comment]
@walterlv 版本 2.13.1 已经发布，优化了通知页面的展示。你更新体验下，看看有没有解决你的问题。

**Comment by walterlv** [comment]
问题解决，非常感谢！

**Comment by derekcoder** [comment]
@walterlv 感谢反馈👍
