### ISSUE TITLE
建议调整通知页面的布局，考虑通知太多时的排版方式

### ISSUE THREAD

**Issue by walterlv** [CoderxforGitHub/Feedback#59]
如下图，我只要一天不点掉通知，就几千条了，于是像这样把他们放在一个页面里面的时候，有些冷门仓库在快速滚动时可能就看不到了。

![image](https://user-images.githubusercontent.com/9959623/59544415-da538c00-8f43-11e9-9adf-07751eca0336.png)

而下面是 GitHub 的网页版通知页面，我可以第一眼看到我最感兴趣的通知。当这部分通知看完之后，我再迅速浏览其他大量通知。全部浏览完就全部标记已读。但标记已读一般是三五天一次，所以基本都能积攒几千条。

![image](https://user-images.githubusercontent.com/9959623/59544447-27376280-8f44-11e9-83cc-61d303b732a3.png)

建议：调整通知页面的排版方式，或者使用多页的方式，以便能够高效的处理大量通知。可以借鉴 GitHub 官方页面，或者自己设计一个更好的呈现方式（当然需要能够适应大量通知的用户）。

**Comment by derekcoder** [comment]
在 v3.1.0 中已经重新设计了。请及时更新体验。

**Comment by walterlv** [comment]
哇……右上角现在有一个选择仓库的功能，非常不错，效率高多啦！

看来国庆节期间你一直在继续开发哟！
