### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by xxxIxxxx** [CoderxforGitHub/Feedback#62]
搜索语言列表增加收藏并置顶，
还有App里的反馈好像坏掉了

**Comment by derekcoder** [comment]
@xxxIxxxx 感谢建议。下个版本会添加置顶语言功能，同时会修复反馈失败问题。

**Comment by derekcoder** [comment]
v3.1.6 已发布。修复了反馈失败问题以及添加了一个常用语言选项。请及时更新体验。
