### ISSUE TITLE
仓库排名标题

### ISSUE THREAD

**Issue by rippleQ** [CoderxforGitHub/Feedback#66]
在选择了spoken language 后，标题栏不跟随 今日/本周/本月 的切换而变化。

iPhone SE 13.3 - V3.2.0(340)

**Comment by derekcoder** [comment]
@rippleQ 收到，下个版本会修复这个问题。感谢反馈。

**Comment by derekcoder** [comment]
Apple 12月23–27 在放假，需要 27 日以后才能上线新版本了。

**Comment by derekcoder** [comment]
已经在 v3.3.0 中修复。感谢反馈
