### ISSUE TITLE
网络请求失败一直打不开页面

### ISSUE THREAD

**Issue by c0pyninj4** [CoderxforGitHub/Feedback#70]
最近老是打不开页面
报错提示网络请求失败啊

iPhone SE 13.3 - V3.3.0(346)

**Comment by derekcoder** [comment]
请问有使用 VPN ？

**Comment by derekcoder** [comment]
用网页访问下 GitHub 网站，看看行不行？网上有说中国很多地区 GitHub 被墙了。
